// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: tcp.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 消息类型枚举
type MsgType int32

const (
	MsgType_MSG_TYPE_UNKNOWN   MsgType = 0 // 未知类型
	MsgType_MSG_TYPE_HEARTBEAT MsgType = 1 // 心跳消息
	MsgType_MSG_TYPE_TASK      MsgType = 2 // 任务
	MsgType_MSG_TYPE_TASKRESP  MsgType = 3 // 任务应答
)

// Enum value maps for MsgType.
var (
	MsgType_name = map[int32]string{
		0: "MSG_TYPE_UNKNOWN",
		1: "MSG_TYPE_HEARTBEAT",
		2: "MSG_TYPE_TASK",
		3: "MSG_TYPE_TASKRESP",
	}
	MsgType_value = map[string]int32{
		"MSG_TYPE_UNKNOWN":   0,
		"MSG_TYPE_HEARTBEAT": 1,
		"MSG_TYPE_TASK":      2,
		"MSG_TYPE_TASKRESP":  3,
	}
)

func (x MsgType) Enum() *MsgType {
	p := new(MsgType)
	*p = x
	return p
}

func (x MsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_tcp_proto_enumTypes[0].Descriptor()
}

func (MsgType) Type() protoreflect.EnumType {
	return &file_tcp_proto_enumTypes[0]
}

func (x MsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgType.Descriptor instead.
func (MsgType) EnumDescriptor() ([]byte, []int) {
	return file_tcp_proto_rawDescGZIP(), []int{0}
}

// 消息类型枚举
type TaskType int32

const (
	TaskType_TASK_TYPE_UNKNOWN  TaskType = 0 // 未知类型
	TaskType_TASK_TYPE_RESETPWD TaskType = 1 // 重置密码
	TaskType_TASK_TYPE_TC       TaskType = 2 // 网卡限速
)

// Enum value maps for TaskType.
var (
	TaskType_name = map[int32]string{
		0: "TASK_TYPE_UNKNOWN",
		1: "TASK_TYPE_RESETPWD",
		2: "TASK_TYPE_TC",
	}
	TaskType_value = map[string]int32{
		"TASK_TYPE_UNKNOWN":  0,
		"TASK_TYPE_RESETPWD": 1,
		"TASK_TYPE_TC":       2,
	}
)

func (x TaskType) Enum() *TaskType {
	p := new(TaskType)
	*p = x
	return p
}

func (x TaskType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskType) Descriptor() protoreflect.EnumDescriptor {
	return file_tcp_proto_enumTypes[1].Descriptor()
}

func (TaskType) Type() protoreflect.EnumType {
	return &file_tcp_proto_enumTypes[1]
}

func (x TaskType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskType.Descriptor instead.
func (TaskType) EnumDescriptor() ([]byte, []int) {
	return file_tcp_proto_rawDescGZIP(), []int{1}
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sn            string                 `protobuf:"bytes,1,opt,name=sn,proto3" json:"sn,omitempty"`
	Ver           string                 `protobuf:"bytes,2,opt,name=ver,proto3" json:"ver,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // 添加时间戳字段，使用int64类型表示Unix时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_tcp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_tcp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_tcp_proto_rawDescGZIP(), []int{0}
}

func (x *Heartbeat) GetSn() string {
	if x != nil {
		return x.Sn
	}
	return ""
}

func (x *Heartbeat) GetVer() string {
	if x != nil {
		return x.Ver
	}
	return ""
}

func (x *Heartbeat) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type DeviceAgent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sn            string                 `protobuf:"bytes,1,opt,name=sn,proto3" json:"sn,omitempty"`
	Ver           string                 `protobuf:"bytes,2,opt,name=ver,proto3" json:"ver,omitempty"`
	RemoteAddr    string                 `protobuf:"bytes,3,opt,name=remote_addr,json=remoteAddr,proto3" json:"remote_addr,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                              // 最后心跳带上来的时间
	LastHeartbear int64                  `protobuf:"varint,5,opt,name=last_heartbear,json=lastHeartbear,proto3" json:"last_heartbear,omitempty"` // 最后心跳时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceAgent) Reset() {
	*x = DeviceAgent{}
	mi := &file_tcp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceAgent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceAgent) ProtoMessage() {}

func (x *DeviceAgent) ProtoReflect() protoreflect.Message {
	mi := &file_tcp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceAgent.ProtoReflect.Descriptor instead.
func (*DeviceAgent) Descriptor() ([]byte, []int) {
	return file_tcp_proto_rawDescGZIP(), []int{1}
}

func (x *DeviceAgent) GetSn() string {
	if x != nil {
		return x.Sn
	}
	return ""
}

func (x *DeviceAgent) GetVer() string {
	if x != nil {
		return x.Ver
	}
	return ""
}

func (x *DeviceAgent) GetRemoteAddr() string {
	if x != nil {
		return x.RemoteAddr
	}
	return ""
}

func (x *DeviceAgent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *DeviceAgent) GetLastHeartbear() int64 {
	if x != nil {
		return x.LastHeartbear
	}
	return 0
}

// 任务结构体
type Task struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	TaskId     string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TaskType   TaskType               `protobuf:"varint,2,opt,name=task_type,json=taskType,proto3,enum=protos.TaskType" json:"task_type,omitempty"`
	Timestamp  int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Sn         string                 `protobuf:"bytes,4,opt,name=sn,proto3" json:"sn,omitempty"`                                   // 设备SN
	AccessName string                 `protobuf:"bytes,5,opt,name=access_name,json=accessName,proto3" json:"access_name,omitempty"` // 接入服务名
	// 重置密码字段
	Username      string `protobuf:"bytes,6,opt,name=username,proto3" json:"username,omitempty"`
	Pwd           string `protobuf:"bytes,7,opt,name=pwd,proto3" json:"pwd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_tcp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_tcp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_tcp_proto_rawDescGZIP(), []int{2}
}

func (x *Task) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Task) GetTaskType() TaskType {
	if x != nil {
		return x.TaskType
	}
	return TaskType_TASK_TYPE_UNKNOWN
}

func (x *Task) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Task) GetSn() string {
	if x != nil {
		return x.Sn
	}
	return ""
}

func (x *Task) GetAccessName() string {
	if x != nil {
		return x.AccessName
	}
	return ""
}

func (x *Task) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Task) GetPwd() string {
	if x != nil {
		return x.Pwd
	}
	return ""
}

// 任务响应
type TaskResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TaskType      TaskType               `protobuf:"varint,2,opt,name=task_type,json=taskType,proto3,enum=protos.TaskType" json:"task_type,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Sn            string                 `protobuf:"bytes,4,opt,name=sn,proto3" json:"sn,omitempty"`                                   // 设备SN
	AccessName    string                 `protobuf:"bytes,5,opt,name=access_name,json=accessName,proto3" json:"access_name,omitempty"` // 接入服务名
	Resp          string                 `protobuf:"bytes,6,opt,name=resp,proto3" json:"resp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResp) Reset() {
	*x = TaskResp{}
	mi := &file_tcp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResp) ProtoMessage() {}

func (x *TaskResp) ProtoReflect() protoreflect.Message {
	mi := &file_tcp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResp.ProtoReflect.Descriptor instead.
func (*TaskResp) Descriptor() ([]byte, []int) {
	return file_tcp_proto_rawDescGZIP(), []int{3}
}

func (x *TaskResp) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResp) GetTaskType() TaskType {
	if x != nil {
		return x.TaskType
	}
	return TaskType_TASK_TYPE_UNKNOWN
}

func (x *TaskResp) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TaskResp) GetSn() string {
	if x != nil {
		return x.Sn
	}
	return ""
}

func (x *TaskResp) GetAccessName() string {
	if x != nil {
		return x.AccessName
	}
	return ""
}

func (x *TaskResp) GetResp() string {
	if x != nil {
		return x.Resp
	}
	return ""
}

var File_tcp_proto protoreflect.FileDescriptor

const file_tcp_proto_rawDesc = "" +
	"\n" +
	"\ttcp.proto\x12\x06protos\"K\n" +
	"\tHeartbeat\x12\x0e\n" +
	"\x02sn\x18\x01 \x01(\tR\x02sn\x12\x10\n" +
	"\x03ver\x18\x02 \x01(\tR\x03ver\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"\x95\x01\n" +
	"\vDeviceAgent\x12\x0e\n" +
	"\x02sn\x18\x01 \x01(\tR\x02sn\x12\x10\n" +
	"\x03ver\x18\x02 \x01(\tR\x03ver\x12\x1f\n" +
	"\vremote_addr\x18\x03 \x01(\tR\n" +
	"remoteAddr\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12%\n" +
	"\x0elast_heartbear\x18\x05 \x01(\x03R\rlastHeartbear\"\xcb\x01\n" +
	"\x04Task\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12-\n" +
	"\ttask_type\x18\x02 \x01(\x0e2\x10.protos.TaskTypeR\btaskType\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x0e\n" +
	"\x02sn\x18\x04 \x01(\tR\x02sn\x12\x1f\n" +
	"\vaccess_name\x18\x05 \x01(\tR\n" +
	"accessName\x12\x1a\n" +
	"\busername\x18\x06 \x01(\tR\busername\x12\x10\n" +
	"\x03pwd\x18\a \x01(\tR\x03pwd\"\xb5\x01\n" +
	"\bTaskResp\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12-\n" +
	"\ttask_type\x18\x02 \x01(\x0e2\x10.protos.TaskTypeR\btaskType\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x0e\n" +
	"\x02sn\x18\x04 \x01(\tR\x02sn\x12\x1f\n" +
	"\vaccess_name\x18\x05 \x01(\tR\n" +
	"accessName\x12\x12\n" +
	"\x04resp\x18\x06 \x01(\tR\x04resp*a\n" +
	"\aMsgType\x12\x14\n" +
	"\x10MSG_TYPE_UNKNOWN\x10\x00\x12\x16\n" +
	"\x12MSG_TYPE_HEARTBEAT\x10\x01\x12\x11\n" +
	"\rMSG_TYPE_TASK\x10\x02\x12\x15\n" +
	"\x11MSG_TYPE_TASKRESP\x10\x03*K\n" +
	"\bTaskType\x12\x15\n" +
	"\x11TASK_TYPE_UNKNOWN\x10\x00\x12\x16\n" +
	"\x12TASK_TYPE_RESETPWD\x10\x01\x12\x10\n" +
	"\fTASK_TYPE_TC\x10\x02B'Z%github.com/liuhengloveyou/pcdn/protosb\x06proto3"

var (
	file_tcp_proto_rawDescOnce sync.Once
	file_tcp_proto_rawDescData []byte
)

func file_tcp_proto_rawDescGZIP() []byte {
	file_tcp_proto_rawDescOnce.Do(func() {
		file_tcp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tcp_proto_rawDesc), len(file_tcp_proto_rawDesc)))
	})
	return file_tcp_proto_rawDescData
}

var file_tcp_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_tcp_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_tcp_proto_goTypes = []any{
	(MsgType)(0),        // 0: protos.MsgType
	(TaskType)(0),       // 1: protos.TaskType
	(*Heartbeat)(nil),   // 2: protos.Heartbeat
	(*DeviceAgent)(nil), // 3: protos.DeviceAgent
	(*Task)(nil),        // 4: protos.Task
	(*TaskResp)(nil),    // 5: protos.TaskResp
}
var file_tcp_proto_depIdxs = []int32{
	1, // 0: protos.Task.task_type:type_name -> protos.TaskType
	1, // 1: protos.TaskResp.task_type:type_name -> protos.TaskType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_tcp_proto_init() }
func file_tcp_proto_init() {
	if File_tcp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tcp_proto_rawDesc), len(file_tcp_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tcp_proto_goTypes,
		DependencyIndexes: file_tcp_proto_depIdxs,
		EnumInfos:         file_tcp_proto_enumTypes,
		MessageInfos:      file_tcp_proto_msgTypes,
	}.Build()
	File_tcp_proto = out.File
	file_tcp_proto_goTypes = nil
	file_tcp_proto_depIdxs = nil
}
